from fastapi import APIRouter, Depends
from fastapi.responses import JSONResponse
from fastapi.encoders import jsonable_encoder

from core.rag.services import RAGService
from core.rag.schema import RAGQueryRequest, RAGQueryResponse
from dependencies import get_rag_service

rag_router = APIRouter()


@rag_router.post("/search", response_model=RAGQueryResponse)
async def rag_search(
    request: RAGQueryRequest,
    rag_service: RAGService = Depends(get_rag_service)
) -> JSONResponse:
    """
    Endpoint to perform RAG (Retrieval Augmented Generation) search.
    
    Searches for similar chunks using vector search and generates a response
    using OpenAI based on the found context.
    
    Args:
        request: Object with query and search parameters
        rag_service: RAG service injected via dependencies
        
    Returns:
        JSON response with found chunks and response generated by OpenAI
    """
    # Use service to perform search and generation
    result = rag_service.search_and_generate(request)
    
    # Return response
    return JSONResponse(status_code=200, content=jsonable_encoder(result))

